@startuml components_diagram

package Data {
    package Payment {
        class PayPalSettings
        class stripeSettings
    }
    package Services {
        class ManufacturerService
        class MediaService
        class MobileService
        class OrderServices
    }
    package Base {
        interface IEntityBaseRepository
        class EntityBaseRepository
        interface EntityBase
    }
    Base --> Services
}

package Controllers {
    class AccountController
    class FilterController
    class HomeController
    class ManufacturersController
    class MediaController
    class MobilesController
    class OrdersController
}



Controllers -[#Green]-> Services
Controllers -[#Blue]-> Models
Controllers -[#Purple]-> Payment
MobilesController --> Utils

Package Models {
    class Address
    class ApplicationUser
    class ErrorViewModel
    class Manufacturer
    class Media
    class Mobile
    class MobileViewModel
    class Order
    class OrderItem
    class searchParamter
    class ShoppingCartItem
    class Specs
    Mobile            *-- Specs           
    Mobile            *-- Manufacturer    
    Mobile            o-- Media           
    ShoppingCartItem  o--  Mobile          
    Order             *-- ApplicationUser 
    Order             *-- OrderItem       
    OrderItem         o-- Mobile
    ApplicationUser   *-- Address
    Order             *-- Address

}

Package Utils {
    class predicateBuilder
    class propSearch
}